version: '3.8'

services:

  # DEV
  pacmusic-dev:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: pacmusic-dev
    environment:
      MINIO_ENDPOINT: ${MINIO_DEV_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_DEV_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_DEV_SECRET_KEY}
    ports:
      - "5000:5000"
    networks:
      - pacmusic-network

  # STG
  pacmusic-stg-1:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: pacmusic-stg-1
    environment:
      MINIO_ENDPOINT: ${MINIO_STG_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_STG_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_STG_SECRET_KEY}
    ports:
      - "5002:5000"
    networks:
      - pacmusic-network

  pacmusic-stg-2:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: pacmusic-stg-2
    environment:
      MINIO_ENDPOINT: ${MINIO_STG_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_STG_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_STG_SECRET_KEY}
    ports:
      - "5003:5000"
    networks:
      - pacmusic-network

  # PROD
  pacmusic-prod-1:
    image: "${APP_IMAGE}:${APP_TAG}"
    container_name: pacmusic-prod-1
    environment:
      MINIO_ENDPOINT: ${MINIO_PROD_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_PROD_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_PROD_SECRET_KEY}
    ports:
      - "5000:5000"
    networks:
      - pacmusic-network

  pacmusic-prod-2:
    image: "${APP_IMAGE}:${APP_TAG}"
    container_name: pacmusic-prod-2
    environment:
      MINIO_ENDPOINT: ${MINIO_PROD_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_PROD_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_PROD_SECRET_KEY}
    ports:
      - "5001:5000"
    networks:
      - pacmusic-network

  # Nginx
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - /etc/ssl/certs
    depends_on:
      - pacmusic-stg-1
      - pacmusic-stg-2
      - pacmusic-prod-1
      - pacmusic-prod-2
    networks:
      - pacmusic-network

  # Certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'if [ ! -d /etc/letsencrypt/live/stg.pac-app.online ]; then certbot certonly --webroot -w /var/www/certbot --email ibnu.fajar94@outlook.com -d stg.pac-app.online --agree-tos --no-eff-email; fi && if [ ! -d /etc/letsencrypt/live/pac-app.online ]; then certbot certonly --webroot -w /var/www/certbot --email ibnu.fajar94@outlook.com -d pac-app.online --agree-tos --no-eff-email; fi && trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  pacmusic-network:
    driver: bridge
    name: pacmusic-network

volumes:
  minio-dev-vol:
    driver: local
    name: minio-dev-vol
