name: Deploy Staging 🚀

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-staging:
    name: Deploy to staging server
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Execute deployment command
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_STG_PATH: ${{ vars.APP_STG_PATH }}
          GIT_URL: ${{ secrets.GIT_URL }}
          MINIO_STG_ENDPOINT: ${{ secrets.MINIO_STG_ENDPOINT }}
          MINIO_STG_ACCESS_KEY: ${{ secrets.MINIO_STG_ACCESS_KEY }}
          MINIO_STG_SECRET_KEY: ${{ secrets.MINIO_STG_SECRET_KEY }}
          APP_STG_PORT_1: ${{ secrets.APP_STG_PORT_1 }}
          APP_STG_PORT_2: ${{ secrets.APP_STG_PORT_2 }}
         
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          envs: APP_STG_PATH,GIT_URL,MINIO_STG_ENDPOINT,MINIO_STG_ACCESS_KEY,MINIO_STG_SECRET_KEY,APP_STG_PORT_1,APP_STG_PORT_2
          script: |
            echo "Debugging: Print non-sensitive environment variables"
            echo "APP_STG_PATH: ${APP_STG_PATH}"
            echo "MINIO_STG_ENDPOINT: ${MINIO_STG_ENDPOINT}"
            echo "APP_STG_PORT_1: ${APP_STG_PORT_1}"
            echo "APP_STG_PORT_2: ${APP_STG_PORT_2}"

            if [[ -d "${APP_STG_PATH}" ]]; then 
              cd ${APP_STG_PATH}
              git config pull.rebase false
              git fetch origin main
              git reset --hard origin/main
            else
              ssh-keyscan github.com > ~/.ssh/known_hosts
              git clone $GIT_URL ${APP_STG_PATH}
              cd ${APP_STG_PATH}
            fi

            echo "Updating environment variables"
            cat << EOF > .env
            APP_STG_PORT_1=${APP_STG_PORT_1}
            APP_STG_PORT_2=${APP_STG_PORT_2}
            MINIO_STG_ENDPOINT=${MINIO_STG_ENDPOINT}
            MINIO_STG_ACCESS_KEY=${MINIO_STG_ACCESS_KEY}
            MINIO_STG_SECRET_KEY=${MINIO_STG_SECRET_KEY}
            EOF

            echo "Generating DH param if not exists"
            if [ ! -f ./nginx/ssl/dhparam.pem ]; then
              sudo mkdir -p ./nginx/ssl
              sudo openssl dhparam -out ./nginx/ssl/dhparam.pem 2048
            fi

            echo "Stopping all services"
            sudo docker compose down

            echo "Starting Nginx and Certbot"
            sudo docker compose up -d nginx certbot
            echo "Waiting for Nginx to start..."
            sleep 10

            echo "Checking Nginx configuration"
            sudo docker compose exec nginx nginx -T

            echo "Running Certbot"
            sudo docker compose run --rm certbot certonly --webroot -w /var/www/certbot -d pac-app.online -d stg.pac-app.online --force-renewal

            echo "Reloading Nginx"
            sudo docker compose exec nginx nginx -s reload

            echo "Starting staging services"
            sudo docker compose up -d pacmusic-stg-1 pacmusic-stg-2

            echo "Checking if services are running"
            sudo docker compose ps

            echo "Checking docker compose logs"
            sudo docker compose logs --tail=50

      - name: Check Endpoint
        run: |
          sleep 20
          curl -v ${{ secrets.STG_URL }}