name: Deploy Staging 🚀

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-staging:
    name: Deploy to staging server
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: Execute deployment command
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_STG_PATH: ${{ vars.APP_STG_PATH }}
          GIT_URL: ${{ secrets.GIT_URL }}
          APP_STG_PORT: ${{ secrets.APP_STG_PORT}}
          APP_STG_PORT_1: ${{ secrets.APP_STG_PORT_1}}
          APP_STG_PORT_2: ${{ secrets.APP_STG_PORT_2}}
          MINIO_STG_ENDPOINT: ${{ secrets.MINIO_STG_ENDPOINT}}
          MINIO_STG_ACCESS_KEY: ${{ secrets.MINIO_STG_ACCESS_KEY}}
          MINIO_STG_SECRET_KEY: ${{ secrets.MINIO_STG_SECRET_KEY}}

        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          envs: APP_STG_PATH, GIT_URL, APP_STG_PORT, APP_STG_PORT_1, APP_STG_PORT_2, MINIO_STG_ENDPOINT, MINIO_STG_ACCESS_KEY, MINIO_STG_SECRET_KEY
          script: |
            if [[ -d "${APP_STG_PATH}" ]]; then 
              cd $APP_STG_PATH
              sudo docker compose down pacmusic-stg-1 pacmusic-stg-2 nginx certbot
              git pull origin main
            else
              ssh-keyscan github.com > ~/.ssh/known_hosts
              git clone $GIT_URL $APP_STG_PATH
              cd $APP_STG_PATH
            fi

            echo "APP_STG_PORT=${{ secrets.APP_STG_PORT }}" > .env
            echo "APP_STG_PORT_1=${{ secrets.APP_STG_PORT_1 }}" >> .env
            echo "APP_STG_PORT_2=${{ secrets.APP_STG_PORT_2 }}" >> .env
            echo "MINIO_STG_ENDPOINT=${{ secrets.MINIO_STG_ENDPOINT }}" >> .env
            echo "MINIO_STG_ACCESS_KEY=${{ secrets.MINIO_STG_ACCESS_KEY }}" >> .env
            echo "MINIO_STG_SECRET_KEY=${{ secrets.MINIO_STG_SECRET_KEY }}" >> .env

            sudo mkdir -p /var/www/certbot

            sudo ln -sf /etc/nginx/sites-available/stg.pac-app.online /etc/nginx/sites-enabled/
            sudo ln -sf /etc/nginx/sites-available/pac-app.online /etc/nginx/sites-enabled/

            sudo docker compose up --build --detach pacmusic-stg-1 pacmusic-stg-2 nginx certbot

            if sudo docker ps | grep -q certbot; then
              echo "Certbot container is running."
            else
              echo "Certbot container is not running. Exiting."
              exit 1
            fi

            sudo docker exec certbot /bin/sh -c "certbot certonly --webroot -w /var/www/certbot -d stg.pac-app.online --non-interactive --agree-tos -m shootbyrealme@gmail.com --force-renewal"

            sudo ln -sf /etc/nginx/snippets/ssl-stg.pac-app.online.conf /etc/nginx/snippets/
            sudo ln -sf /etc/nginx/snippets/ssl-pac-app.online.conf /etc/nginx/snippets/
            sudo docker restart nginx

      - name: Check staging endpoint
        run: |
          sleep 10
          if curl -f http://stg.pac-app.online:${{ secrets.APP_STG_PORT_1 }} || curl -f http://stg.pac-app.online:${{ secrets.APP_STG_PORT_2 }}; then
            echo "HTTP endpoint is accessible."
          else
            echo "HTTP endpoint is not accessible."
            exit 1
          fi
          if curl -f https://stg.pac-app.online; then
            echo "HTTPS endpoint is accessible."
          else
            echo "HTTPS endpoint is not accessible. Restarting Nginx."
            sudo docker restart nginx
            sleep 5
            if ! curl -f https://stg.pac-app.online; then
              echo "HTTPS endpoint is still not accessible. Please check Nginx and SSL configuration."
              exit 1
            fi
          fi
